// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
	"github.com/sqlc-dev/pqtype"
)

type AccountLevelRate struct {
	ID               int32           `json:"id"`
	UserID           uuid.UUID       `json:"user_id"`
	BaseCurrencyID   int32           `json:"base_currency_id"`
	QuoteCurrencyID  int32           `json:"quote_currency_id"`
	Rate             decimal.Decimal `json:"rate"`
	Spread           decimal.Decimal `json:"spread"`
	ValidFrom        sql.NullTime    `json:"valid_from"`
	ValidUntil       sql.NullTime    `json:"valid_until"`
	AutomateRate     bool            `json:"automate_rate"`
	BaseExchangeRate int32           `json:"base_exchange_rate"`
	RateSource       string          `json:"rate_source"`
	Type             string          `json:"type"`
	Version          time.Time       `json:"version"`
}

type AffiliateMerchant struct {
	ID            uuid.UUID `json:"id"`
	ApiKey        string    `json:"api_key"`
	Email         string    `json:"email"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
	WebhookUrl    string    `json:"webhook_url"`
	WebhookSecret string    `json:"webhook_secret"`
}

type AffiliateMerchantWebhookTmp struct {
	ID            uuid.UUID       `json:"id"`
	MerchantID    uuid.UUID       `json:"merchant_id"`
	SwapData      json.RawMessage `json:"swap_data"`
	WebhookStatus int32           `json:"webhook_status"`
	MetaData      json.RawMessage `json:"meta_data"`
	CreatedAt     time.Time       `json:"created_at"`
	UpdatedAt     time.Time       `json:"updated_at"`
}

type AgentDailyDiscount struct {
	ID               int32           `json:"id"`
	UserID           uuid.UUID       `json:"user_id"`
	BaseCurrencyID   int32           `json:"base_currency_id"`
	DiscountMultiple decimal.Decimal `json:"discount_multiple"`
	DiscountAmount   decimal.Decimal `json:"discount_amount"`
	TopUpAmount      decimal.Decimal `json:"top_up_amount"`
	StartTimestamp   sql.NullTime    `json:"start_timestamp"`
	EndTimestamp     sql.NullTime    `json:"end_timestamp"`
}

type AgentDiscount struct {
	ID               int32           `json:"id"`
	BaseCurrencyID   int32           `json:"base_currency_id"`
	DiscountAmount   decimal.Decimal `json:"discount_amount"`
	DiscountMultiple decimal.Decimal `json:"discount_multiple"`
}

type Bank struct {
	ID          int32        `json:"id"`
	Name        string       `json:"name"`
	Slug        string       `json:"slug"`
	Code        string       `json:"code"`
	Longcode    string       `json:"longcode"`
	Gateway     string       `json:"gateway"`
	PayWithBank bool         `json:"pay_with_bank"`
	Active      bool         `json:"active"`
	Country     string       `json:"country"`
	Currency    string       `json:"currency"`
	Type        string       `json:"type"`
	IsDeleted   bool         `json:"is_deleted"`
	CreatedAt   sql.NullTime `json:"created_at"`
	UpdatedAt   sql.NullTime `json:"updated_at"`
}

type BankAccountNumber struct {
	ID            int32  `json:"id"`
	AccountNumber string `json:"account_number"`
	AccountName   string `json:"account_name"`
	CurrencyCode  string `json:"currency_code"`
	Note          string `json:"note"`
}

type BannedCredential struct {
	ID         int64     `json:"id"`
	FieldType  string    `json:"field_type"`
	FieldValue string    `json:"field_value"`
	IpAddress  string    `json:"ip_address"`
	UserAgent  string    `json:"user_agent"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type Business struct {
	ID                      uuid.UUID       `json:"id"`
	Name                    string          `json:"name"`
	RegistrationNumber      string          `json:"registration_number"`
	BusinessNature          string          `json:"business_nature"`
	BusinessCategory        string          `json:"business_category"`
	Address1                string          `json:"address1"`
	Address2                string          `json:"address2"`
	City                    string          `json:"city"`
	PostCode                string          `json:"post_code"`
	State                   string          `json:"state"`
	Country                 string          `json:"country"`
	Website                 string          `json:"website"`
	ProductDescription      string          `json:"product_description"`
	RegistrationDate        string          `json:"registration_date"`
	TradingAddress          string          `json:"trading_address"`
	TradingLevel            string          `json:"trading_level"`
	PrimaryContactType      string          `json:"primary_contact_type"`
	Phone                   string          `json:"phone"`
	Email                   string          `json:"email"`
	ContactName             string          `json:"contact_name"`
	CreatedAt               time.Time       `json:"created_at"`
	UpdatedAt               time.Time       `json:"updated_at"`
	CreatedBy               uuid.UUID       `json:"created_by"`
	IncorporationRegion     json.RawMessage `json:"incorporation_region"`
	ApprovalStatus          sql.NullString  `json:"approval_status"`
	ApprovalStatusUpdatedAt sql.NullTime    `json:"approval_status_updated_at"`
	ApprovalStatusUpdatedBy uuid.NullUUID   `json:"approval_status_updated_by"`
	ApprovalStatusReason    sql.NullString  `json:"approval_status_reason"`
}

type BusinessOwner struct {
	ID                      uuid.UUID      `json:"id"`
	BusinessID              uuid.UUID      `json:"business_id"`
	OwnerRole               string         `json:"owner_role"`
	FirstName               string         `json:"first_name"`
	LastName                string         `json:"last_name"`
	Dob                     string         `json:"dob"`
	IDType                  string         `json:"id_type"`
	IDNumber                string         `json:"id_number"`
	Nationality             string         `json:"nationality"`
	Address1                string         `json:"address1"`
	Address2                string         `json:"address2"`
	State                   string         `json:"state"`
	City                    string         `json:"city"`
	Country                 string         `json:"country"`
	IsUbo                   bool           `json:"is_ubo"`
	HoldingRatio            int16          `json:"holding_ratio"`
	CreatedAt               time.Time      `json:"created_at"`
	UpdatedAt               time.Time      `json:"updated_at"`
	LinkedUserID            uuid.NullUUID  `json:"linked_user_id"`
	ApprovalStatus          sql.NullString `json:"approval_status"`
	ApprovalStatusUpdatedAt sql.NullTime   `json:"approval_status_updated_at"`
	ApprovalStatusUpdatedBy uuid.NullUUID  `json:"approval_status_updated_by"`
	ApprovalStatusReason    sql.NullString `json:"approval_status_reason"`
}

type CacheEntry struct {
	Key       string       `json:"key"`
	Value     []byte       `json:"value"`
	ExpireAt  sql.NullTime `json:"expire_at"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
}

type Company struct {
	ID        int64     `json:"id"`
	ShortName string    `json:"short_name"`
	LongName  string    `json:"long_name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Currency struct {
	ID                      int32  `json:"id"`
	Name                    string `json:"name"`
	DecimalPlaces           int16  `json:"decimal_places"`
	Active                  bool   `json:"active"`
	CanHaveWallet           bool   `json:"can_have_wallet"`
	CanSwapFrom             bool   `json:"can_swap_from"`
	CanSwapTo               bool   `json:"can_swap_to"`
	Code                    string `json:"code"`
	SupportedPaymentSchemes string `json:"supported_payment_schemes"`
}

type CurrencyConfigurationsSystem struct {
	ID          int32        `json:"id"`
	ConfigKey   string       `json:"config_key"`
	ConfigValue string       `json:"config_value"`
	CurrencyID  int32        `json:"currency_id"`
	CreatedAt   sql.NullTime `json:"created_at"`
	UpdatedAt   sql.NullTime `json:"updated_at"`
}

type CurrencyConfigurationsUser struct {
	ID          int32        `json:"id"`
	ConfigKey   string       `json:"config_key"`
	ConfigValue string       `json:"config_value"`
	CurrencyID  int32        `json:"currency_id"`
	UserID      uuid.UUID    `json:"user_id"`
	CreatedAt   sql.NullTime `json:"created_at"`
	UpdatedAt   sql.NullTime `json:"updated_at"`
}

type Customer struct {
	ID        uuid.UUID `json:"id"`
	OwnerID   uuid.UUID `json:"owner_id"`
	Name      string    `json:"name"`
	Phone     string    `json:"phone"`
	Email     string    `json:"email"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Dealer struct {
	ID                uuid.UUID `json:"id"`
	Name              string    `json:"name"`
	BankAccountNumber string    `json:"bank_account_number"`
	BankCode          string    `json:"bank_code"`
	CreatedBy         uuid.UUID `json:"created_by"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
}

type Document struct {
	ID             uuid.UUID `json:"id"`
	Model          string    `json:"model"`
	ModelID        uuid.UUID `json:"model_id"`
	UserID         uuid.UUID `json:"user_id"`
	DocumentType   string    `json:"document_type"`
	DocumentNumber string    `json:"document_number"`
	Bucket         string    `json:"bucket"`
	DocumentPath   string    `json:"document_path"`
	Storage        string    `json:"storage"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

type DynamicKycResult struct {
	ID               uuid.UUID `json:"id"`
	KycRequirementID uuid.UUID `json:"kyc_requirement_id"`
	Field            string    `json:"field"`
	Value            string    `json:"value"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
}

type ExchangeRate struct {
	ID               int32           `json:"id"`
	BaseCurrencyID   int32           `json:"base_currency_id"`
	QuoteCurrencyID  int32           `json:"quote_currency_id"`
	Rate             decimal.Decimal `json:"rate"`
	Spread           decimal.Decimal `json:"spread"`
	ValidFrom        sql.NullTime    `json:"valid_from"`
	ValidUntil       sql.NullTime    `json:"valid_until"`
	AutomateRate     bool            `json:"automate_rate"`
	RateSource       string          `json:"rate_source"`
	BaseExchangeRate int32           `json:"base_exchange_rate"`
	Type             string          `json:"type"`
	Version          time.Time       `json:"version"`
}

type FormAssignment struct {
	ID               uuid.UUID             `json:"id"`
	FormDefinitionID uuid.UUID             `json:"form_definition_id"`
	AssignmentType   string                `json:"assignment_type"`
	AssignmentValue  string                `json:"assignment_value"`
	Conditions       pqtype.NullRawMessage `json:"conditions"`
	Priority         int32                 `json:"priority"`
	ValidFrom        sql.NullTime          `json:"valid_from"`
	ValidUntil       sql.NullTime          `json:"valid_until"`
	CreatedAt        time.Time             `json:"created_at"`
	CreatedBy        uuid.NullUUID         `json:"created_by"`
}

type FormDefinition struct {
	ID                        uuid.UUID       `json:"id"`
	Name                      string          `json:"name"`
	Slug                      string          `json:"slug"`
	Description               string          `json:"description"`
	FormType                  string          `json:"form_type"`
	Version                   int32           `json:"version"`
	IsActive                  bool            `json:"is_active"`
	IsMultiStep               bool            `json:"is_multi_step"`
	RequiresApproval          bool            `json:"requires_approval"`
	IsEditableAfterSubmission bool            `json:"is_editable_after_submission"`
	ApprovalWorkflow          json.RawMessage `json:"approval_workflow"`
	CreatedAt                 time.Time       `json:"created_at"`
	UpdatedAt                 time.Time       `json:"updated_at"`
	CreatedBy                 uuid.NullUUID   `json:"created_by"`
}

type FormDynamicOption struct {
	ID            uuid.UUID       `json:"id"`
	Name          string          `json:"name"`
	SourceType    string          `json:"source_type"`
	SourceConfig  json.RawMessage `json:"source_config"`
	CacheDuration int32           `json:"cache_duration"`
	CreatedAt     time.Time       `json:"created_at"`
}

type FormEvent struct {
	ID               uuid.UUID       `json:"id"`
	FormDefinitionID uuid.UUID       `json:"form_definition_id"`
	EventType        string          `json:"event_type"`
	HandlerType      string          `json:"handler_type"`
	HandlerConfig    json.RawMessage `json:"handler_config"`
	IsActive         bool            `json:"is_active"`
	CreatedAt        time.Time       `json:"created_at"`
}

type FormField struct {
	ID               uuid.UUID       `json:"id"`
	FormDefinitionID uuid.UUID       `json:"form_definition_id"`
	FormStepID       uuid.UUID       `json:"form_step_id"`
	FieldName        string          `json:"field_name"`
	FieldType        string          `json:"field_type"`
	Label            json.RawMessage `json:"label"`
	Placeholder      json.RawMessage `json:"placeholder"`
	HelpText         json.RawMessage `json:"help_text"`
	ValidationRules  json.RawMessage `json:"validation_rules"`
	Options          json.RawMessage `json:"options"`
	DisplayOrder     int32           `json:"display_order"`
	IsRequired       bool            `json:"is_required"`
	IsReadonly       bool            `json:"is_readonly"`
	DefaultValue     string          `json:"default_value"`
	ConditionalLogic json.RawMessage `json:"conditional_logic"`
	FileConfig       json.RawMessage `json:"file_config"`
	CreatedAt        time.Time       `json:"created_at"`
	UpdatedAt        time.Time       `json:"updated_at"`
}

type FormPersistenceConfig struct {
	ID                  uuid.UUID       `json:"id"`
	FormDefinitionID    uuid.UUID       `json:"form_definition_id"`
	PersistenceMode     string          `json:"persistence_mode"`
	TargetConfigs       json.RawMessage `json:"target_configs"`
	FieldMappings       json.RawMessage `json:"field_mappings"`
	TransformationRules json.RawMessage `json:"transformation_rules"`
	ValidationHooks     json.RawMessage `json:"validation_hooks"`
	CreatedAt           time.Time       `json:"created_at"`
	UpdatedAt           time.Time       `json:"updated_at"`
}

type FormStep struct {
	ID               uuid.UUID `json:"id"`
	FormDefinitionID uuid.UUID `json:"form_definition_id"`
	StepNumber       int32     `json:"step_number"`
	Name             string    `json:"name"`
	Description      string    `json:"description"`
	IsOptional       bool      `json:"is_optional"`
	CreatedAt        time.Time `json:"created_at"`
}

type FormStepProgress struct {
	ID               uuid.UUID             `json:"id"`
	FormSubmissionID uuid.NullUUID         `json:"form_submission_id"`
	FormStepID       uuid.NullUUID         `json:"form_step_id"`
	StepNumber       int32                 `json:"step_number"`
	Status           sql.NullString        `json:"status"`
	CompletedAt      sql.NullTime          `json:"completed_at"`
	Data             pqtype.NullRawMessage `json:"data"`
	CreatedAt        sql.NullTime          `json:"created_at"`
	UpdatedAt        sql.NullTime          `json:"updated_at"`
}

type FormSubmission struct {
	ID                   uuid.UUID       `json:"id"`
	FormDefinitionID     uuid.UUID       `json:"form_definition_id"`
	UserID               uuid.UUID       `json:"user_id"`
	SubmissionData       json.RawMessage `json:"submission_data"`
	Status               string          `json:"status"`
	ApprovalStatus       string          `json:"approval_status"`
	ApprovalNotes        string          `json:"approval_notes"`
	ApprovedBy           uuid.NullUUID   `json:"approved_by"`
	ApprovedAt           time.Time       `json:"approved_at"`
	Metadata             json.RawMessage `json:"metadata"`
	CreatedAt            time.Time       `json:"created_at"`
	UpdatedAt            time.Time       `json:"updated_at"`
	CurrentStepNumber    sql.NullInt32   `json:"current_step_number"`
	CompletionPercentage sql.NullInt32   `json:"completion_percentage"`
}

type FormSubmissionFile struct {
	ID               uuid.UUID `json:"id"`
	FormSubmissionID uuid.UUID `json:"form_submission_id"`
	FieldName        string    `json:"field_name"`
	FileName         string    `json:"file_name"`
	FilePath         string    `json:"file_path"`
	FileSize         int64     `json:"file_size"`
	MimeType         string    `json:"mime_type"`
	Bucket           string    `json:"bucket"`
	StorageProvider  string    `json:"storage_provider"`
	UploadedAt       time.Time `json:"uploaded_at"`
}

type IdentityVerificationDatum struct {
	ID                 int64          `json:"id"`
	UserID             uuid.UUID      `json:"user_id"`
	CreatedAt          time.Time      `json:"created_at"`
	UpdatedAt          time.Time      `json:"updated_at"`
	Gender             sql.NullString `json:"gender"`
	Address            sql.NullString `json:"address"`
	City               sql.NullString `json:"city"`
	HouseNo            sql.NullString `json:"house_no"`
	LastName           sql.NullString `json:"last_name"`
	FirstName          sql.NullString `json:"first_name"`
	DateOfBirth        sql.NullTime   `json:"date_of_birth"`
	DocumentType       sql.NullString `json:"document_type"`
	DocumentNumber     sql.NullString `json:"document_number"`
	DocumentCountry    sql.NullString `json:"document_country"`
	DocumentValidFrom  sql.NullTime   `json:"document_valid_from"`
	DocumentValidUntil sql.NullTime   `json:"document_valid_until"`
	Provider           string         `json:"provider"`
	Scope              string         `json:"scope"`
}

type InflowBankTransfer struct {
	ID        uuid.UUID       `json:"id"`
	UserID    uuid.UUID       `json:"user_id"`
	WalletID  uuid.UUID       `json:"wallet_id"`
	Amount    decimal.Decimal `json:"amount"`
	Provider  string          `json:"provider"`
	Status    string          `json:"status"`
	Payload   json.RawMessage `json:"payload"`
	Remark    string          `json:"remark"`
	CreatedAt time.Time       `json:"created_at"`
	UpdatedAt time.Time       `json:"updated_at"`
}

type Job struct {
	Key         string    `json:"key"`
	JobID       string    `json:"job_id"`
	Minutes     int32     `json:"minutes"`
	LastRunAt   time.Time `json:"last_run_at"`
	Enable      bool      `json:"enable"`
	Description string    `json:"description"`
}

type KycRequirement struct {
	ID          uuid.UUID       `json:"id"`
	Title       string          `json:"title"`
	Description string          `json:"description"`
	Payload     json.RawMessage `json:"payload"`
	Target      string          `json:"target"`
	TargetID    string          `json:"target_id"`
	Deadline    sql.NullTime    `json:"deadline"`
	Status      string          `json:"status"`
	CreatedAt   time.Time       `json:"created_at"`
}

type KycRequirementsUser struct {
	ID               uuid.UUID       `json:"id"`
	KycRequirementID uuid.UUID       `json:"kyc_requirement_id"`
	UserID           uuid.UUID       `json:"user_id"`
	Payload          json.RawMessage `json:"payload"`
	Status           string          `json:"status"`
	CreatedAt        time.Time       `json:"created_at"`
}

type Log struct {
	ID        int32           `json:"id"`
	LogData   json.RawMessage `json:"log_data"`
	CreatedAt sql.NullTime    `json:"created_at"`
}

type MoneysendrRecipient struct {
	ID               uuid.UUID       `json:"id"`
	Email            string          `json:"email"`
	Phone            string          `json:"phone"`
	BankName         string          `json:"bank_name"`
	BankCode         string          `json:"bank_code"`
	AccountNumber    string          `json:"account_number"`
	AccountName      string          `json:"account_name"`
	CreatedAt        time.Time       `json:"created_at"`
	UpdatedAt        time.Time       `json:"updated_at"`
	Remark           string          `json:"remark"`
	Status           string          `json:"status"`
	Exchangeratedata json.RawMessage `json:"exchangeratedata"`
	Fromcurrencycode string          `json:"fromcurrencycode"`
	Tocurrencycode   string          `json:"tocurrencycode"`
	AmountIn         decimal.Decimal `json:"amount_in"`
	AmountOut        decimal.Decimal `json:"amount_out"`
	Fees             decimal.Decimal `json:"fees"`
	Rate             decimal.Decimal `json:"rate"`
	InternalRemark   string          `json:"internal_remark"`
}

type Permission struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
	Code string `json:"code"`
}

type ProcessedBankTransfer struct {
	TransRef  string    `json:"trans_ref"`
	Provider  string    `json:"provider"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Recipient struct {
	ID        uuid.UUID       `json:"id"`
	UserID    uuid.UUID       `json:"user_id"`
	Scheme    string          `json:"scheme"`
	Currency  string          `json:"currency"`
	Data      json.RawMessage `json:"data"`
	CreatedAt sql.NullTime    `json:"created_at"`
	UpdatedAt sql.NullTime    `json:"updated_at"`
}

type Referral struct {
	ID          uuid.UUID `json:"id"`
	CountryCode string    `json:"country_code"`
	Phone       string    `json:"phone"`
	RefereeID   uuid.UUID `json:"referee_id"`
	Status      string    `json:"status"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type SchemaPaymentFeesConfig struct {
	ID           int32           `json:"id"`
	SchemaName   string          `json:"schema_name"`
	IsPercentage bool            `json:"is_percentage"`
	Amount       decimal.Decimal `json:"amount"`
	MaxAmount    decimal.Decimal `json:"max_amount"`
	UpdatedAt    sql.NullTime    `json:"updated_at"`
}

type Session struct {
	ID           uuid.UUID `json:"id"`
	UserID       uuid.UUID `json:"user_id"`
	RefreshToken string    `json:"refresh_token"`
	IpAddress    string    `json:"ip_address"`
	UserAgent    string    `json:"user_agent"`
	IsBlocked    bool      `json:"is_blocked"`
	ExpiresAt    time.Time `json:"expires_at"`
	CreatedAt    time.Time `json:"created_at"`
}

type Settlement struct {
	ID            uuid.UUID       `json:"id"`
	TransactionID uuid.UUID       `json:"transaction_id"`
	Amount        decimal.Decimal `json:"amount"`
	Source        string          `json:"source"`
	Status        string          `json:"status"`
	CreatedAt     time.Time       `json:"created_at"`
	UpdatedAt     time.Time       `json:"updated_at"`
	ExecutedBy    uuid.UUID       `json:"executed_by"`
	Payload       json.RawMessage `json:"payload"`
}

type SystemConfiguration struct {
	ConfigKey   string       `json:"config_key"`
	ConfigValue string       `json:"config_value"`
	CreatedAt   sql.NullTime `json:"created_at"`
	UpdatedAt   sql.NullTime `json:"updated_at"`
}

type Token struct {
	Hash      string    `json:"hash"`
	UserID    uuid.UUID `json:"user_id"`
	Expiry    time.Time `json:"expiry"`
	Scope     string    `json:"scope"`
	CreatedAt time.Time `json:"created_at"`
	Provider  string    `json:"provider"`
}

type Transaction struct {
	ID                 uuid.UUID       `json:"id"`
	UserID             uuid.UUID       `json:"user_id"`
	WalletID           uuid.UUID       `json:"wallet_id"`
	Amount             decimal.Decimal `json:"amount"`
	Type               string          `json:"type"`
	Source             string          `json:"source"`
	Action             string          `json:"action"`
	Status             string          `json:"status"`
	Tag                string          `json:"tag"`
	CurrencyID         int32           `json:"currency_id"`
	PaymentMethod      string          `json:"payment_method"`
	FeesAmount         decimal.Decimal `json:"fees_amount"`
	Rate               decimal.Decimal `json:"rate"`
	FeesIsPercentage   bool            `json:"fees_is_percentage"`
	Payload            json.RawMessage `json:"payload"`
	CreatedAt          time.Time       `json:"created_at"`
	UpdatedAt          time.Time       `json:"updated_at"`
	RequiresSettlement bool            `json:"requires_settlement"`
	SettlementStatus   string          `json:"settlement_status"`
	IsInvoiceUploaded  bool            `json:"is_invoice_uploaded"`
	TrackingNumber     string          `json:"tracking_number"`
	Gateway            string          `json:"gateway"`
	CompanyName        string          `json:"company_name"`
}

type TransactionHistory struct {
	ID            int64           `json:"id"`
	TransactionID uuid.UUID       `json:"transaction_id"`
	UserID        uuid.UUID       `json:"user_id"`
	Amount        decimal.Decimal `json:"amount"`
	Payload       json.RawMessage `json:"payload"`
	OldStatus     string          `json:"old_status"`
	NewStatus     string          `json:"new_status"`
	Reason        string          `json:"reason"`
	CreatedAt     time.Time       `json:"created_at"`
}

type User struct {
	ID                uuid.UUID    `json:"id"`
	Email             string       `json:"email"`
	CountryCode       string       `json:"country_code"`
	Phone             string       `json:"phone"`
	Password          string       `json:"password"`
	CreatedAt         time.Time    `json:"created_at"`
	UpdatedAt         time.Time    `json:"updated_at"`
	PasswordChangedAt time.Time    `json:"password_changed_at"`
	Active            bool         `json:"active"`
	SuspendedAt       sql.NullTime `json:"suspended_at"`
	AccountType       string       `json:"account_type"`
	FirstName         string       `json:"first_name"`
	MiddleName        string       `json:"middle_name"`
	LastName          string       `json:"last_name"`
	BusinessName      string       `json:"business_name"`
	Address           string       `json:"address"`
	AccountNumber     string       `json:"account_number"`
	BankName          string       `json:"bank_name"`
	BankCode          string       `json:"bank_code"`
	Bvn               string       `json:"bvn"`
	City              string       `json:"city"`
	State             string       `json:"state"`
	Zipcode           string       `json:"zipcode"`
	KycVerified       string       `json:"kyc_verified"`
	KycVerifiedAt     sql.NullTime `json:"kyc_verified_at"`
	Version           int32        `json:"version"`
}

type UserAction struct {
	ID        uuid.UUID       `json:"id"`
	UserID    uuid.UUID       `json:"user_id"`
	Action    string          `json:"action"`
	Message   string          `json:"message"`
	Payload   json.RawMessage `json:"payload"`
	CreatedAt time.Time       `json:"created_at"`
	UpdatedAt time.Time       `json:"updated_at"`
}

type UserFailedLogin struct {
	ID             int32        `json:"id"`
	UserIdentity   string       `json:"user_identity"`
	Provider       string       `json:"provider"`
	FailedAttempts int32        `json:"failed_attempts"`
	LastFailedAt   time.Time    `json:"last_failed_at"`
	BannedUntil    sql.NullTime `json:"banned_until"`
}

type UserIdentityDocument struct {
	ID             uuid.UUID `json:"id"`
	UserID         uuid.UUID `json:"user_id"`
	DocumentType   string    `json:"document_type"`
	DocumentNumber string    `json:"document_number"`
	Bucket         string    `json:"bucket"`
	DocumentPath   string    `json:"document_path"`
	Storage        string    `json:"storage"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

type UserMetum struct {
	UserID      uuid.UUID      `json:"user_id"`
	Key         string         `json:"key"`
	Value       sql.NullString `json:"value"`
	Datatype    string         `json:"datatype"`
	LastUpdated sql.NullTime   `json:"last_updated"`
}

type UserSetting struct {
	ID        int32        `json:"id"`
	UserID    uuid.UUID    `json:"user_id"`
	Key       string       `json:"key"`
	Value     string       `json:"value"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type UsersPermission struct {
	UserID       uuid.UUID `json:"user_id"`
	PermissionID int64     `json:"permission_id"`
}

type VeriffWebhook struct {
	ID               uuid.UUID       `json:"id"`
	Payload          json.RawMessage `json:"payload"`
	PayloadType      string          `json:"payload_type"`
	Status           string          `json:"status"`
	CreatedAt        time.Time       `json:"created_at"`
	UpdatedAt        time.Time       `json:"updated_at"`
	SessionID        string          `json:"session_id"`
	PayloadStructure string          `json:"payload_structure"`
	Scope            string          `json:"scope"`
}

type VirtualAccountsNumber struct {
	ID                uuid.UUID `json:"id"`
	Provider          string    `json:"provider"`
	UserID            uuid.UUID `json:"user_id"`
	WalletID          uuid.UUID `json:"wallet_id"`
	AccountNumber     string    `json:"account_number"`
	AccountName       string    `json:"account_name"`
	ExternalID        string    `json:"external_id"`
	BankName          string    `json:"bank_name"`
	BankCode          string    `json:"bank_code"`
	BankSlug          string    `json:"bank_slug"`
	CurrencyCode      string    `json:"currency_code"`
	CreatedAt         time.Time `json:"created_at"`
	ExternalWalletID  string    `json:"external_wallet_id"`
	Network           string    `json:"network"`
	RoutingCodeType   string    `json:"routing_code_type"`
	RoutingCode       string    `json:"routing_code"`
	AccountNumberType string    `json:"account_number_type"`
	BankCountry       string    `json:"bank_country"`
	BankCity          string    `json:"bank_city"`
	BankAddress       string    `json:"bank_address"`
	BankPostCode      string    `json:"bank_post_code"`
}

type Wallet struct {
	ID         uuid.UUID       `json:"id"`
	UserID     uuid.UUID       `json:"user_id"`
	CurrencyID int32           `json:"currency_id"`
	Balance    decimal.Decimal `json:"balance"`
	Hash       string          `json:"hash"`
	CreatedAt  time.Time       `json:"created_at"`
	UpdatedAt  time.Time       `json:"updated_at"`
	Version    int32           `json:"version"`
	Locked     bool            `json:"locked"`
}

type WorkflowCheckpoint struct {
	ID             int64           `json:"id"`
	UserID         uuid.UUID       `json:"user_id"`
	CreatedAt      time.Time       `json:"created_at"`
	UpdatedAt      time.Time       `json:"updated_at"`
	CheckpointName string          `json:"checkpoint_name"`
	CheckpointData json.RawMessage `json:"checkpoint_data"`
	Status         string          `json:"status"`
	BatchID        string          `json:"batch_id"`
}
