// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

type Querier interface {
	ActivateUser(ctx context.Context, id uuid.UUID) (User, error)
	AddPermissionForUser(ctx context.Context, arg AddPermissionForUserParams) (UsersPermission, error)
	AddToCompanies(ctx context.Context, arg AddToCompaniesParams) (Company, error)
	ArchiveReferral(ctx context.Context, phone string) (Referral, error)
	CalculateExchangeRate(ctx context.Context, arg CalculateExchangeRateParams) (CalculateExchangeRateRow, error)
	ChangeCurrencyActiveState(ctx context.Context, arg ChangeCurrencyActiveStateParams) (Currency, error)
	CreateAccountLevelExchangeRate(ctx context.Context, arg CreateAccountLevelExchangeRateParams) (AccountLevelRate, error)
	CreateAffiliateMerchant(ctx context.Context, arg CreateAffiliateMerchantParams) (AffiliateMerchant, error)
	CreateAffiliateMerchantWebhookMetaData(ctx context.Context, arg CreateAffiliateMerchantWebhookMetaDataParams) (AffiliateMerchantWebhookTmp, error)
	CreateAgentDailyDiscount(ctx context.Context, arg CreateAgentDailyDiscountParams) (AgentDailyDiscount, error)
	CreateBankAccountNumber(ctx context.Context, arg CreateBankAccountNumberParams) (BankAccountNumber, error)
	CreateBannedEntry(ctx context.Context, arg CreateBannedEntryParams) (BannedCredential, error)
	CreateBusinessKYB(ctx context.Context, arg CreateBusinessKYBParams) (Business, error)
	CreateBusinessOwner(ctx context.Context, arg CreateBusinessOwnerParams) (BusinessOwner, error)
	CreateCheckpoint(ctx context.Context, arg CreateCheckpointParams) error
	CreateCronJob(ctx context.Context, arg CreateCronJobParams) error
	CreateCurrency(ctx context.Context, arg CreateCurrencyParams) (Currency, error)
	CreateCurrencySettingSystem(ctx context.Context, arg CreateCurrencySettingSystemParams) (CurrencyConfigurationsSystem, error)
	CreateCurrencySettingUser(ctx context.Context, arg CreateCurrencySettingUserParams) (CurrencyConfigurationsUser, error)
	CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error)
	CreateDailyDiscount(ctx context.Context, arg CreateDailyDiscountParams) (AgentDiscount, error)
	CreateDealer(ctx context.Context, arg CreateDealerParams) (Dealer, error)
	CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error)
	CreateDynamicOption(ctx context.Context, arg CreateDynamicOptionParams) (FormDynamicOption, error)
	CreateExchangeRate(ctx context.Context, arg CreateExchangeRateParams) (ExchangeRate, error)
	CreateFormAssignment(ctx context.Context, arg CreateFormAssignmentParams) (FormAssignment, error)
	CreateFormDefinition(ctx context.Context, arg CreateFormDefinitionParams) (FormDefinition, error)
	CreateFormEvent(ctx context.Context, arg CreateFormEventParams) (FormEvent, error)
	CreateFormField(ctx context.Context, arg CreateFormFieldParams) (FormField, error)
	CreateFormStep(ctx context.Context, arg CreateFormStepParams) (FormStep, error)
	CreateFormSubmission(ctx context.Context, arg CreateFormSubmissionParams) (FormSubmission, error)
	CreateFormSubmissionFile(ctx context.Context, arg CreateFormSubmissionFileParams) (FormSubmissionFile, error)
	CreateIdentityDocument(ctx context.Context, arg CreateIdentityDocumentParams) (UserIdentityDocument, error)
	CreateInflowBankTransfer(ctx context.Context, arg CreateInflowBankTransferParams) (InflowBankTransfer, error)
	CreateKYCRequirement(ctx context.Context, arg CreateKYCRequirementParams) error
	CreateLog(ctx context.Context, logData json.RawMessage) (Log, error)
	CreateMoneySendrRecipient(ctx context.Context, arg CreateMoneySendrRecipientParams) (MoneysendrRecipient, error)
	CreatePermission(ctx context.Context, arg CreatePermissionParams) (Permission, error)
	CreatePersistenceConfig(ctx context.Context, arg CreatePersistenceConfigParams) (FormPersistenceConfig, error)
	CreateProcessesBankTransfer(ctx context.Context, arg CreateProcessesBankTransferParams) error
	CreateRecipient(ctx context.Context, arg CreateRecipientParams) (Recipient, error)
	CreateReferral(ctx context.Context, arg CreateReferralParams) (Referral, error)
	CreateSchemaPaymentFeeConfig(ctx context.Context, arg CreateSchemaPaymentFeeConfigParams) (SchemaPaymentFeesConfig, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateSettlement(ctx context.Context, arg CreateSettlementParams) (Settlement, error)
	CreateStepProgress(ctx context.Context, arg CreateStepProgressParams) (FormStepProgress, error)
	CreateToken(ctx context.Context, arg CreateTokenParams) (Token, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	CreateTransactionHistory(ctx context.Context, arg CreateTransactionHistoryParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserAction(ctx context.Context, arg CreateUserActionParams) (UserAction, error)
	CreateUserKYCRequirement(ctx context.Context, arg CreateUserKYCRequirementParams) (KycRequirementsUser, error)
	CreateUserSetting(ctx context.Context, arg CreateUserSettingParams) error
	CreateUserVirtualAccountNumber(ctx context.Context, arg CreateUserVirtualAccountNumberParams) (VirtualAccountsNumber, error)
	CreateVeriffWebhook(ctx context.Context, arg CreateVeriffWebhookParams) (VeriffWebhook, error)
	CreateWallet(ctx context.Context, arg CreateWalletParams) (Wallet, error)
	DeactivateUser(ctx context.Context, id uuid.UUID) (User, error)
	DeleteAccountLevelExchangeRate(ctx context.Context, id int32) error
	DeleteAllAccountLevelExchangeRate(ctx context.Context) error
	DeleteAllAgentDailyDiscount(ctx context.Context) error
	DeleteAllCurrencySettingUser(ctx context.Context, arg DeleteAllCurrencySettingUserParams) error
	DeleteAllExchangeRate(ctx context.Context) error
	DeleteBankAccountNumber(ctx context.Context, id int32) error
	DeleteBannedEntry(ctx context.Context, id int64) error
	DeleteBannedEntryByField(ctx context.Context, arg DeleteBannedEntryByFieldParams) error
	DeleteCheckpoint(ctx context.Context, id int64) error
	DeleteCompanyByShortName(ctx context.Context, shortName string) error
	DeleteCurrency(ctx context.Context, id int32) error
	DeleteCustomer(ctx context.Context, ownerID uuid.UUID) error
	DeleteDailyDiscountByID(ctx context.Context, id int32) error
	DeleteDealer(ctx context.Context, id uuid.UUID) error
	DeleteDocument(ctx context.Context, id uuid.UUID) error
	DeleteExchangeRate(ctx context.Context, id int32) error
	DeleteFormSubmissionFile(ctx context.Context, id uuid.UUID) error
	DeleteIdentityDocument(ctx context.Context, id uuid.UUID) error
	DeleteLogsOlderThanNDays(ctx context.Context, dollar_1 interface{}) error
	DeletePermissionFromUser(ctx context.Context, arg DeletePermissionFromUserParams) error
	DeleteReferral(ctx context.Context, arg DeleteReferralParams) error
	DeleteSchemaPaymentFeeConfig(ctx context.Context, schemaName string) error
	DeleteSession(ctx context.Context, id uuid.UUID) error
	DeleteUserDocument(ctx context.Context, arg DeleteUserDocumentParams) error
	DeleteUserKYCRequirementResults(ctx context.Context, kycRequirementID uuid.UUID) error
	DeleteUserRecipient(ctx context.Context, arg DeleteUserRecipientParams) error
	DeleteUserRecipients(ctx context.Context, userID uuid.UUID) error
	DeleteUserTokens(ctx context.Context, arg DeleteUserTokensParams) error
	DeleteWallet(ctx context.Context, id uuid.UUID) error
	FindCustomerByEmail(ctx context.Context, arg FindCustomerByEmailParams) (Customer, error)
	FindCustomerById(ctx context.Context, arg FindCustomerByIdParams) (Customer, error)
	FindCustomerByPhone(ctx context.Context, arg FindCustomerByPhoneParams) (Customer, error)
	FindDailyDiscountByBaseCurrencyID(ctx context.Context, baseCurrencyID int32) (AgentDiscount, error)
	FindDailyDiscountByID(ctx context.Context, id int32) (AgentDiscount, error)
	FindExistingUserToken(ctx context.Context, arg FindExistingUserTokenParams) (Token, error)
	FindProcessesBankTransfer(ctx context.Context, arg FindProcessesBankTransferParams) (ProcessedBankTransfer, error)
	FindUserVirtualAccountNumber(ctx context.Context, arg FindUserVirtualAccountNumberParams) (VirtualAccountsNumber, error)
	GetAccountLevelExchangeRate(ctx context.Context, arg GetAccountLevelExchangeRateParams) (AccountLevelRate, error)
	GetActiveCurrencies(ctx context.Context, active sql.NullBool) ([]Currency, error)
	GetActiveKYCRequirement(ctx context.Context, arg GetActiveKYCRequirementParams) (KycRequirement, error)
	GetActiveKYCRequirementByID(ctx context.Context, id uuid.UUID) (KycRequirement, error)
	GetAffiliateMerchantByAPIKey(ctx context.Context, apiKey string) (AffiliateMerchant, error)
	GetAffiliateMerchantByEmail(ctx context.Context, email string) (AffiliateMerchant, error)
	GetAffiliateMerchantByID(ctx context.Context, id uuid.UUID) (AffiliateMerchant, error)
	GetAffiliateMerchantWebhookMetaDatasByWebhookStatus(ctx context.Context, webhookStatus int32) ([]AffiliateMerchantWebhookTmp, error)
	GetAgentDailyDiscount(ctx context.Context, arg GetAgentDailyDiscountParams) (AgentDailyDiscount, error)
	GetAllAutomatedExchangeRates(ctx context.Context) ([]ExchangeRate, error)
	GetAllAutomatedExchangeRatesThatAreDependencies(ctx context.Context) ([]GetAllAutomatedExchangeRatesThatAreDependenciesRow, error)
	GetAllAutomatedExchangeRatesWithDependencies(ctx context.Context) ([]GetAllAutomatedExchangeRatesWithDependenciesRow, error)
	GetAllBankAccountNumbers(ctx context.Context) ([]BankAccountNumber, error)
	GetAllBankAccountNumbersByCurrency(ctx context.Context, currencyCode string) ([]BankAccountNumber, error)
	GetAllBanks(ctx context.Context) ([]Bank, error)
	GetAllCurrencies(ctx context.Context) ([]Currency, error)
	GetAllDailyDiscounts(ctx context.Context) ([]AgentDiscount, error)
	GetAllDealers(ctx context.Context) ([]GetAllDealersRow, error)
	GetAllPermissions(ctx context.Context) ([]Permission, error)
	GetAllStepProgress(ctx context.Context, formSubmissionID uuid.NullUUID) ([]FormStepProgress, error)
	GetAllUserPermissions(ctx context.Context, id uuid.UUID) ([]GetAllUserPermissionsRow, error)
	GetAutoExchangeRatesByBaseCurrency(ctx context.Context, arg GetAutoExchangeRatesByBaseCurrencyParams) ([]GetAutoExchangeRatesByBaseCurrencyRow, error)
	GetBank(ctx context.Context, id int32) (Bank, error)
	GetBankByCode(ctx context.Context, code string) (Bank, error)
	GetBannedEntryByField(ctx context.Context, arg GetBannedEntryByFieldParams) (BannedCredential, error)
	GetBusinessByID(ctx context.Context, id uuid.UUID) (Business, error)
	GetBusinessByName(ctx context.Context, name string) (Business, error)
	GetBusinessCreatedByUser(ctx context.Context, createdBy uuid.UUID) (Business, error)
	GetBusinessCreatedByUserByBusinessID(ctx context.Context, arg GetBusinessCreatedByUserByBusinessIDParams) (Business, error)
	GetBusinessOwner(ctx context.Context, id uuid.UUID) (BusinessOwner, error)
	GetBusinessOwnerByID(ctx context.Context, arg GetBusinessOwnerByIDParams) (BusinessOwner, error)
	GetBusinessOwnerByLinkedUser(ctx context.Context, linkedUserID uuid.NullUUID) (BusinessOwner, error)
	GetBusinessOwnersByBusinessID(ctx context.Context, businessID uuid.UUID) ([]BusinessOwner, error)
	GetCheckpoint(ctx context.Context, arg GetCheckpointParams) (WorkflowCheckpoint, error)
	GetCompanies(ctx context.Context) ([]Company, error)
	GetCompany(ctx context.Context, id int64) (Company, error)
	GetCompanyByShortName(ctx context.Context, shortName string) (Company, error)
	GetCronJob(ctx context.Context, key string) (Job, error)
	GetCronJobs(ctx context.Context) ([]Job, error)
	GetCurrency(ctx context.Context, id int32) (Currency, error)
	GetCurrencyByCode(ctx context.Context, code string) (Currency, error)
	GetCurrencySetting(ctx context.Context, arg GetCurrencySettingParams) ([]GetCurrencySettingRow, error)
	GetCurrencySettingUser(ctx context.Context, arg GetCurrencySettingUserParams) ([]CurrencyConfigurationsUser, error)
	GetCurrencySettingsSystem(ctx context.Context, currencyID int32) ([]CurrencyConfigurationsSystem, error)
	GetDailySwap(ctx context.Context, arg GetDailySwapParams) ([]Transaction, error)
	GetDealer(ctx context.Context, id uuid.UUID) (Dealer, error)
	GetDocumentByModel(ctx context.Context, arg GetDocumentByModelParams) (Document, error)
	GetDocumentsByModel(ctx context.Context, arg GetDocumentsByModelParams) ([]Document, error)
	GetDynamicOption(ctx context.Context, id uuid.UUID) (FormDynamicOption, error)
	GetDynamicOptionByName(ctx context.Context, name string) (FormDynamicOption, error)
	GetExchangeRate(ctx context.Context, arg GetExchangeRateParams) (ExchangeRate, error)
	GetExchangeRateByID(ctx context.Context, id int32) (GetExchangeRateByIDRow, error)
	GetExchangeRateByPeerType(ctx context.Context, arg GetExchangeRateByPeerTypeParams) (GetExchangeRateByPeerTypeRow, error)
	GetExchangeRatePeer(ctx context.Context, arg GetExchangeRatePeerParams) (GetExchangeRatePeerRow, error)
	GetFormAssignments(ctx context.Context, arg GetFormAssignmentsParams) ([]GetFormAssignmentsRow, error)
	GetFormDefinition(ctx context.Context, id uuid.UUID) (FormDefinition, error)
	GetFormDefinitionBySlug(ctx context.Context, slug string) (FormDefinition, error)
	GetFormEvents(ctx context.Context, arg GetFormEventsParams) ([]FormEvent, error)
	GetFormFields(ctx context.Context, formDefinitionID uuid.UUID) ([]FormField, error)
	GetFormFieldsByStep(ctx context.Context, formStepID uuid.UUID) ([]FormField, error)
	GetFormSteps(ctx context.Context, formDefinitionID uuid.UUID) ([]FormStep, error)
	GetFormSubmission(ctx context.Context, id uuid.UUID) (FormSubmission, error)
	GetFormSubmissionByUserAndForm(ctx context.Context, arg GetFormSubmissionByUserAndFormParams) (FormSubmission, error)
	GetFormSubmissionFiles(ctx context.Context, formSubmissionID uuid.UUID) ([]FormSubmissionFile, error)
	GetInflowBankTransferById(ctx context.Context, id uuid.UUID) (InflowBankTransfer, error)
	GetKYCDocuments(ctx context.Context, modelID uuid.UUID) ([]Document, error)
	GetKYCRequirement(ctx context.Context, arg GetKYCRequirementParams) (KycRequirement, error)
	GetKYCRequirementByID(ctx context.Context, id uuid.UUID) (KycRequirement, error)
	GetKYCRequirements(ctx context.Context) ([]KycRequirement, error)
	GetKYCRequirementsByTarget(ctx context.Context, arg GetKYCRequirementsByTargetParams) ([]KycRequirement, error)
	GetLogs(ctx context.Context, limit int32) ([]Log, error)
	GetLogsByJSONContent(ctx context.Context, arg GetLogsByJSONContentParams) ([]Log, error)
	GetLogsByMessage(ctx context.Context, arg GetLogsByMessageParams) ([]Log, error)
	GetManyUserKYCRequirements(ctx context.Context, userID uuid.UUID) ([]GetManyUserKYCRequirementsRow, error)
	GetOTPPendingSettlementByProvider(ctx context.Context, arg GetOTPPendingSettlementByProviderParams) (Settlement, error)
	GetOneDocumentByID(ctx context.Context, id uuid.UUID) (Document, error)
	GetOneDocumentByModel(ctx context.Context, arg GetOneDocumentByModelParams) (Document, error)
	GetOtherUserByEmail(ctx context.Context, arg GetOtherUserByEmailParams) (User, error)
	GetOtherUserByPhone(ctx context.Context, arg GetOtherUserByPhoneParams) (User, error)
	GetPaginatedInflowBankTransfers(ctx context.Context, arg GetPaginatedInflowBankTransfersParams) ([]GetPaginatedInflowBankTransfersRow, error)
	GetPermission(ctx context.Context, id int64) (Permission, error)
	GetPermissionByCode(ctx context.Context, code string) (Permission, error)
	GetPermissionForUser(ctx context.Context, arg GetPermissionForUserParams) (UsersPermission, error)
	GetPermissionsForUser(ctx context.Context, id uuid.UUID) ([]string, error)
	GetPersistenceConfig(ctx context.Context, formDefinitionID uuid.UUID) (FormPersistenceConfig, error)
	GetProspectiveReferralCount(ctx context.Context, refereeID uuid.UUID) (int64, error)
	GetReferralByID(ctx context.Context, id uuid.UUID) (Referral, error)
	GetReferralByPhone(ctx context.Context, phone string) (Referral, error)
	GetSchemaPaymentFeeConfig(ctx context.Context, schemaName string) (SchemaPaymentFeesConfig, error)
	GetSchemaPaymentFeeConfigs(ctx context.Context) ([]SchemaPaymentFeesConfig, error)
	GetSession(ctx context.Context, id uuid.UUID) (Session, error)
	GetSettlement(ctx context.Context, id uuid.UUID) (Settlement, error)
	GetStepProgress(ctx context.Context, arg GetStepProgressParams) (FormStepProgress, error)
	GetStepProgressBySubmissionAndNumber(ctx context.Context, arg GetStepProgressBySubmissionAndNumberParams) (FormStepProgress, error)
	GetSystemSettings(ctx context.Context) ([]SystemConfiguration, error)
	GetTransaction(ctx context.Context, id uuid.UUID) (Transaction, error)
	GetTransactionBySchemeAndID(ctx context.Context, arg GetTransactionBySchemeAndIDParams) (Transaction, error)
	GetTransactionHistories(ctx context.Context, arg GetTransactionHistoriesParams) ([]TransactionHistory, error)
	GetTransactionSchemeByID(ctx context.Context, id uuid.UUID) (interface{}, error)
	GetTransactionSettlements(ctx context.Context, arg GetTransactionSettlementsParams) ([]Settlement, error)
	GetTransactionTotalSettlement(ctx context.Context, transactionID uuid.UUID) (decimal.Decimal, error)
	GetUnprocessedInflow(ctx context.Context, arg GetUnprocessedInflowParams) ([]InflowBankTransfer, error)
	GetUser(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByPhone(ctx context.Context, phone string) (User, error)
	GetUserDocument(ctx context.Context, arg GetUserDocumentParams) (Document, error)
	GetUserDynamicKYCResults(ctx context.Context, kycRequirementID uuid.UUID) ([]DynamicKycResult, error)
	GetUserIDVDocsByType(ctx context.Context, arg GetUserIDVDocsByTypeParams) ([]Document, error)
	GetUserIdentityDocument(ctx context.Context, userID uuid.UUID) (UserIdentityDocument, error)
	GetUserIdentityDocuments(ctx context.Context, userID uuid.UUID) ([]UserIdentityDocument, error)
	GetUserIdentityVerificationDocuments(ctx context.Context, modelID uuid.UUID) ([]Document, error)
	GetUserKYCRequirement(ctx context.Context, arg GetUserKYCRequirementParams) (KycRequirementsUser, error)
	GetUserPermissionByCode(ctx context.Context, arg GetUserPermissionByCodeParams) (GetUserPermissionByCodeRow, error)
	GetUserRecipient(ctx context.Context, arg GetUserRecipientParams) (Recipient, error)
	GetUserReferrals(ctx context.Context, refereeID uuid.UUID) ([]Referral, error)
	GetUserSubmittedKYC(ctx context.Context, userID uuid.UUID) (KycRequirementsUser, error)
	GetUserSubmittedKYCRequirement(ctx context.Context, arg GetUserSubmittedKYCRequirementParams) (KycRequirementsUser, error)
	GetUserTransactionByManyStatus(ctx context.Context, arg GetUserTransactionByManyStatusParams) (Transaction, error)
	GetUserTransactionByStatus(ctx context.Context, arg GetUserTransactionByStatusParams) (Transaction, error)
	GetUserVerificationDataByProvider(ctx context.Context, arg GetUserVerificationDataByProviderParams) (IdentityVerificationDatum, error)
	GetUserVirtualAccountByAccountNumber(ctx context.Context, arg GetUserVirtualAccountByAccountNumberParams) (VirtualAccountsNumber, error)
	GetUserVirtualAccountByCurrencyCode(ctx context.Context, arg GetUserVirtualAccountByCurrencyCodeParams) (VirtualAccountsNumber, error)
	GetUserVirtualAccountByProvider(ctx context.Context, arg GetUserVirtualAccountByProviderParams) (VirtualAccountsNumber, error)
	GetUserVirtualAccountByWalletIDProvider(ctx context.Context, arg GetUserVirtualAccountByWalletIDProviderParams) (VirtualAccountsNumber, error)
	GetUserVirtualAccounts(ctx context.Context, userID uuid.UUID) ([]VirtualAccountsNumber, error)
	GetUserWalletByCurrency(ctx context.Context, arg GetUserWalletByCurrencyParams) (Wallet, error)
	GetUserWallets(ctx context.Context, userID uuid.UUID) ([]GetUserWalletsRow, error)
	GetVeriffWebhookBySessionId(ctx context.Context, arg GetVeriffWebhookBySessionIdParams) (VeriffWebhook, error)
	GetVirtualAccountNumberByProvider(ctx context.Context, arg GetVirtualAccountNumberByProviderParams) (VirtualAccountsNumber, error)
	GetWallet(ctx context.Context, id uuid.UUID) (Wallet, error)
	InsertUserIdentityVerificationData(ctx context.Context, arg InsertUserIdentityVerificationDataParams) (IdentityVerificationDatum, error)
	ListFormDefinitions(ctx context.Context, arg ListFormDefinitionsParams) ([]FormDefinition, error)
	ListFormSubmissions(ctx context.Context, arg ListFormSubmissionsParams) ([]FormSubmission, error)
	MoneySendrFindTransaction(ctx context.Context, arg MoneySendrFindTransactionParams) (MoneysendrRecipient, error)
	MoneySendrGetTransactionById(ctx context.Context, id uuid.UUID) (MoneysendrRecipient, error)
	MoneySendrGetTransactionByStatus(ctx context.Context, arg MoneySendrGetTransactionByStatusParams) (MoneysendrRecipient, error)
	MoneySendrUpdateTransactionState(ctx context.Context, arg MoneySendrUpdateTransactionStateParams) (MoneysendrRecipient, error)
	ReportGetTransactionInfo(ctx context.Context) ([]ReportGetTransactionInfoRow, error)
	ReportGetWalletBalances(ctx context.Context) ([]ReportGetWalletBalancesRow, error)
	ResetAllCrons(ctx context.Context) error
	SearchLogsByMessageLike(ctx context.Context, arg SearchLogsByMessageLikeParams) ([]Log, error)
	UpdateAccountLevelExchangeRate(ctx context.Context, arg UpdateAccountLevelExchangeRateParams) (AccountLevelRate, error)
	UpdateAffiliateMerchantAPIKey(ctx context.Context, arg UpdateAffiliateMerchantAPIKeyParams) (AffiliateMerchant, error)
	UpdateAffiliateMerchantWebhookData(ctx context.Context, arg UpdateAffiliateMerchantWebhookDataParams) (AffiliateMerchant, error)
	UpdateAffiliateMerchantWebhookStatus(ctx context.Context, arg UpdateAffiliateMerchantWebhookStatusParams) (AffiliateMerchantWebhookTmp, error)
	UpdateBusinessDetails(ctx context.Context, arg UpdateBusinessDetailsParams) (Business, error)
	UpdateBusinessOwnerByID(ctx context.Context, arg UpdateBusinessOwnerByIDParams) (BusinessOwner, error)
	UpdateCheckpointStatus(ctx context.Context, arg UpdateCheckpointStatusParams) error
	UpdateCompanyByID(ctx context.Context, arg UpdateCompanyByIDParams) (Company, error)
	UpdateCronJob(ctx context.Context, arg UpdateCronJobParams) error
	UpdateCronStatus(ctx context.Context, arg UpdateCronStatusParams) error
	UpdateCurrency(ctx context.Context, arg UpdateCurrencyParams) (Currency, error)
	UpdateCurrencySettingSystem(ctx context.Context, arg UpdateCurrencySettingSystemParams) (CurrencyConfigurationsSystem, error)
	UpdateCurrencySettingUser(ctx context.Context, arg UpdateCurrencySettingUserParams) (CurrencyConfigurationsUser, error)
	UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) (Customer, error)
	UpdateDailyDiscount(ctx context.Context, arg UpdateDailyDiscountParams) (AgentDiscount, error)
	UpdateDocument(ctx context.Context, arg UpdateDocumentParams) (Document, error)
	UpdateExchangeRate(ctx context.Context, arg UpdateExchangeRateParams) (ExchangeRate, error)
	UpdateFormDefinition(ctx context.Context, arg UpdateFormDefinitionParams) (FormDefinition, error)
	UpdateFormSubmission(ctx context.Context, arg UpdateFormSubmissionParams) (FormSubmission, error)
	UpdateInflowBankTransferStatus(ctx context.Context, arg UpdateInflowBankTransferStatusParams) (InflowBankTransfer, error)
	UpdateKYCRequirement(ctx context.Context, arg UpdateKYCRequirementParams) error
	UpdatePersistenceConfig(ctx context.Context, arg UpdatePersistenceConfigParams) (FormPersistenceConfig, error)
	UpdateRecipient(ctx context.Context, arg UpdateRecipientParams) (Recipient, error)
	UpdateSchemaPaymentFeeConfig(ctx context.Context, arg UpdateSchemaPaymentFeeConfigParams) (SchemaPaymentFeesConfig, error)
	UpdateSettlementStatus(ctx context.Context, arg UpdateSettlementStatusParams) (Settlement, error)
	UpdateStepProgress(ctx context.Context, arg UpdateStepProgressParams) (FormStepProgress, error)
	UpdateSubmissionProgress(ctx context.Context, arg UpdateSubmissionProgressParams) (FormSubmission, error)
	UpdateSystemSetting(ctx context.Context, arg UpdateSystemSettingParams) (SystemConfiguration, error)
	UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error)
	UpdateTransactionInvoiceStatus(ctx context.Context, id uuid.UUID) (Transaction, error)
	UpdateTransactionInvoiceUploadStatus(ctx context.Context, arg UpdateTransactionInvoiceUploadStatusParams) (Transaction, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserIdentityVerificationData(ctx context.Context, arg UpdateUserIdentityVerificationDataParams) (IdentityVerificationDatum, error)
	UpdateUserKYCApproval(ctx context.Context, arg UpdateUserKYCApprovalParams) error
	UpdateUserKYCRequirementStatus(ctx context.Context, arg UpdateUserKYCRequirementStatusParams) error
	UpdateUserSetting(ctx context.Context, arg UpdateUserSettingParams) error
	UpdateVeriffWebhookStatus(ctx context.Context, arg UpdateVeriffWebhookStatusParams) (VeriffWebhook, error)
	UpdateWalletBalance(ctx context.Context, arg UpdateWalletBalanceParams) (Wallet, error)
	UpdateWalletHash(ctx context.Context, arg UpdateWalletHashParams) (Wallet, error)
	UpsertUserSetting(ctx context.Context, arg UpsertUserSettingParams) error
	ValidateAccountLevelExchangeRateExistence(ctx context.Context, arg ValidateAccountLevelExchangeRateExistenceParams) (int64, error)
	ValidateExchangeRateExistence(ctx context.Context, arg ValidateExchangeRateExistenceParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
